from datetime import date, datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from ..database.base import Base


class Memory(Base):
    __tablename__ = "memories"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    source: Mapped[str] = mapped_column(
        String(50),
        default="chat",
        nullable=False,
    )

    # AI embedding (384-dimensional vector)
    embedding: Mapped[list[float] | None] = mapped_column(
        Vector(384),
        nullable=True,
    )

    # Structured metadata extracted from the memory
    extracted_data: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
    )

    # Date extracted from temporal expressions (e.g., "tomorrow")
    temporal_date: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    user: Mapped["User"] = relationship(
        "User",
        back_populates="memories",
    )

    # Memory category (Work, Personal, Health, etc.)
    category: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    # Importance score generated by AI
    importance: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # Auto-generated tags
    tags: Mapped[list | None] = mapped_column(
        JSON,
        nullable=True,
    )

    # Memory sentiment
    sentiment: Mapped[str | None] = mapped_column(
        String(30),
        nullable=True,
    )

    # Confidence score of extraction/classification
    confidence: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # Number of times this memory has been retrieved
    access_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )

    # Last time this memory was accessed
    last_accessed: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )