"""add_retrieval_logs_table

Revision ID: 454c1e2c396f
Revises: c74d1cbf4878
Create Date: 2026-08-01 15:04:57.919014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '454c1e2c396f'
down_revision: Union[str, Sequence[str], None] = 'c74d1cbf4878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_request_logs', 'retrieval_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_request_logs', 'selected_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_request_logs', 'average_similarity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'average_importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'average_context_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'precision_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'recall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'response_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ai_request_logs', 'response_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_request_logs', 'embedding_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'retrieval_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'ranking_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'context_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'prompt_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'llm_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'total_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_request_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_request_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_request_logs', 'total_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'llm_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'prompt_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'context_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'ranking_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'retrieval_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'embedding_time_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'response_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_request_logs', 'response_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ai_request_logs', 'recall_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'precision_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'average_context_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'average_importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'average_similarity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_request_logs', 'selected_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_request_logs', 'retrieval_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
