"""add_system_metrics_table

Revision ID: 45ed6c7c9c64
Revises: b30f84fe0e66
Create Date: 2026-08-01 16:38:02.125904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ed6c7c9c64'
down_revision: Union[str, Sequence[str], None] = 'b30f84fe0e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
