"""add memory metadata fields

Revision ID: 5f6b6f20c449
Revises: 951c2e5cc744
Create Date: 2026-07-19 22:49:51.290534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6b6f20c449'
down_revision: Union[str, Sequence[str], None] = '951c2e5cc744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('memories', sa.Column('importance', sa.Float(), nullable=True))
    op.add_column('memories', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('memories', sa.Column('sentiment', sa.String(length=30), nullable=True))
    op.add_column('memories', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column(
    "memories",
    sa.Column(
        "access_count",
        sa.Integer(),
        nullable=False,
        server_default="0",
    ),
)
    op.add_column('memories', sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'last_accessed')
    op.drop_column('memories', 'access_count')
    op.drop_column('memories', 'confidence')
    op.drop_column('memories', 'sentiment')
    op.drop_column('memories', 'tags')
    op.drop_column('memories', 'importance')
    op.drop_column('memories', 'category')
    # ### end Alembic commands ###
