"""add extracted_data to memories

Revision ID: 6e6bbdb98272
Revises: 169719b2ba98
Create Date: 2026-07-19 11:23:04.968822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6bbdb98272'
down_revision: Union[str, Sequence[str], None] = '169719b2ba98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('extracted_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'extracted_data')
    # ### end Alembic commands ###
