"""Add temporal_date to memories

Revision ID: 951c2e5cc744
Revises: 6e6bbdb98272
Create Date: 2026-07-19 13:01:46.107114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951c2e5cc744'
down_revision: Union[str, Sequence[str], None] = '6e6bbdb98272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('temporal_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'temporal_date')
    # ### end Alembic commands ###
