"""add_ai_request_logs_table

Revision ID: c74d1cbf4878
Revises: e1d64667eafd
Create Date: 2026-08-01 14:44:52.504100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74d1cbf4878'
down_revision: Union[str, Sequence[str], None] = 'e1d64667eafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=True),
    sa.Column('selected_count', sa.Integer(), nullable=True),
    sa.Column('average_similarity', sa.Float(), nullable=True),
    sa.Column('average_importance', sa.Float(), nullable=True),
    sa.Column('average_context_score', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('response_generated', sa.Boolean(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.Column('embedding_time_ms', sa.Float(), nullable=True),
    sa.Column('retrieval_time_ms', sa.Float(), nullable=True),
    sa.Column('ranking_time_ms', sa.Float(), nullable=True),
    sa.Column('context_time_ms', sa.Float(), nullable=True),
    sa.Column('prompt_time_ms', sa.Float(), nullable=True),
    sa.Column('llm_time_ms', sa.Float(), nullable=True),
    sa.Column('total_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_logs_id'), 'ai_request_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_request_logs_id'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    # ### end Alembic commands ###
