"""add embedding column to memories

Revision ID: da17622f25ef
Revises: 1c2bf5e0043f
Create Date: 2026-07-15 11:50:04.040692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'da17622f25ef'
down_revision: Union[str, Sequence[str], None] = '1c2bf5e0043f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "memories",
    sa.Column(
        "embedding",
        Vector(dim=384),
        nullable=True,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'embedding')
    # ### end Alembic commands ###
