"""add document relationships

Revision ID: f3a3ae401a1d
Revises: 032aec9ca15d
Create Date: 2026-08-09 23:17:56.206286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a3ae401a1d'
down_revision: Union[str, Sequence[str], None] = '032aec9ca15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('relationships', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'relationships')
    # ### end Alembic commands ###
