"""add document category

Revision ID: ffbcfcf3931e
Revises: 6d4e1fa9dbfc
Create Date: 2026-08-08 20:50:43.347796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbcfcf3931e'
down_revision: Union[str, Sequence[str], None] = '6d4e1fa9dbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_category')
    # ### end Alembic commands ###
